controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_offers:
    path: '/api/v1/offers/{param}'
    controller: 'App\Controller\DiscountController::getOffers'
    methods: 'GET'